# Generated by Django 4.2.7 on 2025-07-03 01:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surge', '0002_apistatus'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accept_sms',
            field=models.BooleanField(default=False, help_text='Check if you accept SMS messages'),
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('iata_code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='IATA code must be 3 uppercase letters', regex='^[A-Z]{3}$')])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surge.country')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='closest_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.airport'),
        ),
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('native', 'Native'), ('expert', 'Expert'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], max_length=20)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.language')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_proficiencies', to='users.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Language Proficiencies',
                'unique_together': {('user_profile', 'language')},
            },
        ),
    ]
