# Generated by Django 4.2.7 on 2025-06-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(blank=True, max_length=2, null=True)),
                ('iso3', models.CharField(blank=True, max_length=3, null=True)),
                ('api_id', models.IntegerField(unique=True)),
                ('record_type', models.IntegerField(blank=True, null=True)),
                ('record_type_display', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.IntegerField(blank=True, null=True)),
                ('independent', models.BooleanField(default=True)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('fdrs', models.CharField(blank=True, max_length=10, null=True)),
                ('average_household_size', models.FloatField(blank=True, null=True)),
                ('society_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('translation_module_original_language', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='MolnixTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('molnix_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_type', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('deployment_needed', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('event', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('atype', models.IntegerField(blank=True, null=True)),
                ('atype_display', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('category_display', models.CharField(blank=True, max_length=100, null=True)),
                ('molnix_id', models.IntegerField(blank=True, null=True)),
                ('molnix_status', models.IntegerField(blank=True, null=True)),
                ('molnix_status_display', models.CharField(blank=True, max_length=100, null=True)),
                ('opens', models.DateTimeField(blank=True, null=True)),
                ('closes', models.DateTimeField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('operation', models.TextField(blank=True, null=True)),
                ('translation_module_original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surge.country')),
                ('molnix_tags', models.ManyToManyField(blank=True, to='surge.molnixtag')),
            ],
        ),
    ]
