# Generated by Django 4.2.7 on 2025-07-03 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_run', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'API Statuses',
            },
        ),
    ]
