# Generated by Django 4.2.7 on 2025-07-02 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('task', models.CharField(choices=[('surge.tasks.fetch_surge_alerts', 'Fetch Surge Alerts')], max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('interval', 'Interval'), ('crontab', 'Crontab')], default='interval', max_length=20)),
                ('interval_seconds', models.IntegerField(blank=True, help_text='Interval in seconds', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('interval_minutes', models.IntegerField(blank=True, help_text='Interval in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('interval_hours', models.IntegerField(blank=True, help_text='Interval in hours', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('interval_days', models.IntegerField(blank=True, help_text='Interval in days', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('crontab_minute', models.CharField(blank=True, default='*', help_text="Crontab minute (0-59, '*', '*/15', etc.)", max_length=64, null=True)),
                ('crontab_hour', models.CharField(blank=True, default='*', help_text="Crontab hour (0-23, '*', '*/2', etc.)", max_length=64, null=True)),
                ('crontab_day_of_week', models.CharField(blank=True, default='*', help_text='Crontab day of week (0-6 or mon,tue,wed,thu,fri,sat,sun)', max_length=64, null=True)),
                ('crontab_day_of_month', models.CharField(blank=True, default='*', help_text="Crontab day of month (1-31, '*', etc.)", max_length=64, null=True)),
                ('crontab_month_of_year', models.CharField(blank=True, default='*', help_text='Crontab month of year (1-12, jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec)', max_length=64, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('total_run_count', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled Task',
                'verbose_name_plural': 'Scheduled Tasks',
                'ordering': ['name'],
            },
        ),
    ]
